"""Build the patient-level inputs shared by the Stage-2 CNMA reports."""

from collections.abc import Collection
import json
from pathlib import Path
import subprocess
import tempfile

import pandas as pd


def load_stage1_risk_scores(
    model_path: str | Path,
    model_script_path: str | Path,
    model_data_path: str | Path,
    *,
    rscript: str = "Rscript",
) -> pd.DataFrame:
    """Return patient risk scores generated by the repository's Stage-1 R model.

    Stage 1 stores the fitted model as an RDS file rather than maintaining a
    separate risk-score CSV. This function sources the model's own R script,
    applies ``predict_phq9(..., type="link")`` to its development cohort, and
    returns the identifiers and linear predictor needed by Stage 2.
    """
    model_path = Path(model_path).resolve()
    model_script_path = Path(model_script_path).resolve()
    model_data_path = Path(model_data_path).resolve()

    required = (model_path, model_script_path, model_data_path)
    missing = [path for path in required if not path.exists()]
    if missing:
        formatted = "\n".join(f"- {path}" for path in missing)
        raise FileNotFoundError(
            "Stage-1 input files are missing:\n"
            f"{formatted}\n"
            "Build the phq9_12mo_core dataset and fit risk_score_model.R first."
        )

    with tempfile.TemporaryDirectory(prefix="stage1-risk-scores-") as temp_dir:
        output_path = Path(temp_dir) / "stage1_predictions.csv"
        r_code = f"""
source({json.dumps(str(model_script_path))})
model <- readRDS({json.dumps(str(model_path))})
df <- load_model_data({json.dumps(str(model_data_path))})
newdata <- data.frame(
  y0 = df$phq9_at_baseline,
  age = df$age,
  sex = df$sex
)
scores <- data.frame(
  STUDY_ID = as.character(df$study_id),
  patient_id = as.character(df$patient_id),
  risk_score = predict_phq9(model, newdata, type = "link")
)
data.table::fwrite(scores, {json.dumps(str(output_path))})
"""
        completed = subprocess.run(
            [rscript, "-e", r_code],
            check=False,
            capture_output=True,
            text=True,
        )
        if completed.returncode:
            details = completed.stderr.strip() or completed.stdout.strip()
            raise RuntimeError(f"Stage-1 risk-score prediction failed:\n{details}")

        risk_scores = pd.read_csv(output_path, dtype={"patient_id": "string"})

    required_columns = {"STUDY_ID", "patient_id", "risk_score"}
    missing_columns = required_columns.difference(risk_scores.columns)
    if missing_columns:
        raise ValueError(f"Stage-1 predictions are missing: {sorted(missing_columns)}")
    if risk_scores.duplicated(["STUDY_ID", "patient_id"]).any():
        raise ValueError("Stage-1 predictions contain duplicate study/patient keys.")
    if risk_scores["risk_score"].isna().any():
        raise ValueError("Stage-1 predictions contain missing risk scores.")

    return risk_scores[["STUDY_ID", "patient_id", "risk_score"]]


def create_path_cnma_cohort(
    enriched_path: str | Path,
    risk_scores: pd.DataFrame,
    *,
    follow_up_window: tuple[float, float] = (11.5, 12.5),
    excluded_studies: Collection[str] = ("08_Coventry_2015",),
    randomized_arms: Collection[str] = ("control", "intervention"),
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Return the eligible longitudinal cohort and one Stage-2 row per patient."""
    enriched = pd.read_csv(enriched_path, low_memory=False)
    enriched = enriched.loc[enriched["phq9_total"].mod(1).eq(0)].copy()

    patient_key = ["STUDY_ID", "patient_id"]
    baseline_ids = enriched.loc[enriched["follow_up_months"].eq(0), patient_key].drop_duplicates()
    followup_ids = enriched.loc[
        enriched["follow_up_months"].between(*follow_up_window, inclusive="both"),
        patient_key,
    ].drop_duplicates()

    cohort = enriched.merge(baseline_ids.merge(followup_ids, on=patient_key), on=patient_key)
    cohort = cohort.loc[
        ~cohort["STUDY_ID"].isin(excluded_studies) & cohort["study_arm"].isin(randomized_arms)
    ].copy()

    arms_per_study = cohort.groupby("STUDY_ID")["study_arm"].nunique()
    eligible_studies = arms_per_study.index[arms_per_study.eq(2)]
    cohort = cohort.loc[cohort["STUDY_ID"].isin(eligible_studies)].copy()

    baseline = cohort.loc[cohort["follow_up_months"].eq(0)].drop_duplicates(patient_key)
    followup = cohort.loc[
        cohort["follow_up_months"].between(*follow_up_window, inclusive="both")
    ].copy()
    followup["distance_from_12"] = (followup["follow_up_months"] - 12).abs()
    followup = followup.sort_values(patient_key + ["distance_from_12"]).drop_duplicates(
        patient_key
    )

    analysis_df = (
        baseline[[*patient_key, "study_arm", "age", "sex", "phq9_total"]]
        .rename(columns={"phq9_total": "phq9_baseline"})
        .merge(
            followup[[*patient_key, "follow_up_months", "phq9_total"]].rename(
                columns={
                    "follow_up_months": "outcome_month",
                    "phq9_total": "phq9_12m",
                }
            ),
            on=patient_key,
            validate="one_to_one",
        )
    )

    risk_scores = risk_scores.copy()
    risk_scores["patient_id"] = risk_scores["patient_id"].astype(str)
    analysis_df["patient_id"] = analysis_df["patient_id"].astype(str)
    analysis_df = analysis_df.merge(
        risk_scores,
        on=patient_key,
        how="left",
        validate="one_to_one",
    )

    return cohort, analysis_df
