<<<<<<< HEAD
site_name: dssg-template
# 
site_author: Alexander Richard
=======
site_name: Collaborative Care Analysis
# 
site_author: DSSGx Munich 2026 team
>>>>>>> 865f245 (Address further PR change requests)
# 